#!/usr/bin/python3

# Script to prepare a release using zip/tar.

import platform, os, shutil, sys, subprocess

def main():
    if platform.system() not in [ "Windows", "Linux" ]:
        assert False, f"We do not support '{platform.system()}'!"

    ###################
    #     Config
    ###################

    version      = (len(sys.argv) > 1 and sys.argv[1]) or "0.2-dev"
    release_name = f"btb-{version}"
    folders      = [ "libs", "modules" ]
    build_flags = "use_optimizations use_debug=false use_tracy=false"
    
    readme = f'''
Hello curious programmer!

This is version {version} of the BTB compiler. Read guide and examples on `www.github.com/Emarioo/BetterThanBatch` to begin using the language!

**DISCLAIMER**: Compiler is not finished. You will run in to bugs and problems. The standard library will change and break your code. You can report any bugs you find on the github repository `www.github.com/Emarioo/BetterThanBatch`

The standard library is very experimental, functions for the operating system does not handle errors very well.

The compiler is in early stages and will keep changing a lot until the 1.0.0 release.
One of the planned breaking changes is a redo of the preprocessor and macros.
'''

    ##################
    #     Compile
    ##################

    if platform.system() == "Windows":
        release_name += "-windows-x64"
    elif platform.system() == "Linux":
        release_name += "-linux-x64"
    
    path_release = f"bin/{release_name}"
    path_bin     = f"{path_release}-bin"

    proc = subprocess.run(["git", "rev-parse","--short=12","HEAD"], text=True,stdout=subprocess.PIPE)
    if proc.returncode != 0:
        print(proc.stdout)
        exit(1)

    git_commit = proc.stdout.rstrip().lstrip()
    with open("src/BetBat/const_commit.cpp", "w") as f:
        f.write(f'// THIS FILE IS AUTO-GENERATED BY release.py\nconst char* GIT_COMMIT="{git_commit}";')

    exit(0)

    os.makedirs(path_release, exist_ok=True)
    
    cmd = f"python build.py {build_flags} bin_dir={path_bin} "
    if platform.system() == "Windows":        
        cmd += f"output={path_release}/btb.exe msvc"
    elif platform.system() == "Linux":
        cmd += f"output={path_release}/btb gcc"
    
    print(cmd)
    os.system(cmd)

    ##################
    #    Package
    ###################

    # TODO: Package vscode extension?
    # os.system("cd btb-lang && vsce package")

    for path in folders:
        dst = path_release + "/" + path
        shutil.copytree(path, dst, dirs_exist_ok=True)

    path_readme = path_release + "/README.md"
    with open(path_readme, "w") as f:
        f.write(readme)

    os.makedirs("releases", exist_ok=True)
    path_real_release = f"releases/{release_name}.tar.gz"
    
    if platform.system() == "Windows":
        cmd = f"cd bin && 7z a -tzip ../releases/{release_name}.zip {release_name}/"
    elif platform.system() == "Linux":
        cmd = f"cd bin && tar -czf {release_name}.tar.gz {release_name} && mv {release_name}.tar.gz releases/{release_name}.tar.gz"
        
    print(cmd)
    os.system(cmd)
    
    print(f"Prepared release in {path_real_release}")
    
if __name__ == "__main__":
    main()  